service: pr-peddler
app: pr-peddler
org: fortress

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs16.x
  deploymentBucket:
    name: ${ssm:serverless-deployment-bucket}
    versioning: true
    blockPublicAccess: true

functions:
  pr-peddler:
    handler: handler.probot
    events:
      - http:
          path: /
          method: post

custom:
  deploymentBucket:
    blockPublicAccess: true

plugins:
  - serverless-deployment-bucket
