service: pr-peddler
app: pr-peddler
org: fortress

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  pr-peddler:
    handler: handler.probot
    events:
      - http:
          path: /
          method: post
